version: '3'

services:
  web:
    build:
      dockerfile: dockerfile.prod
      context: .
    command: gunicorn OPL.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8001:8000"
    networks:
      - production
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./opl-backup.sql:/docker-entrypoint-initdb.d/opl-backup.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - production
volumes:
  postgres_data:
