version: '3'

services:
  web:
    build: . #Build from current directory 
    command: ${DOCKER_RUN}
    volumes: #Map current directory to backend directory 
      - .:/backend
    ports:
      - "8000:8080"
    dns: 
      - 212.227.123.16
      - 8.8.8.8
    networks:
      - development
  db:
    image: postgres
    restart: always 
    ports: 
      - 127.0.0.1:5433:5432
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: opl-dev
    volumes: 
      - ./opl-backup.sql:/docker-entrypoint-initdb.d/opl-backup.sql 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - development
  


  

    
