version: '3'

services:
  web:
    build: . #Build from current directory 
    command: python3 manage.py runserver 
    volumes: #Map current directory to backend directory 
      -.:/backend
    ports:
    - "8000:8000"
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: OPL
    volumes: 
      - ./opl-backup.sql:/docker-entrypoint-initdb.d/opl-backup.sql
      - postgres_data:/var/lib/postgresql/data

  

    
